# Codemagic CI/CD для Kabinet
# Используем YAML-конфигурацию для контроля версий Xcode и Flutter

workflows:
  ios-release:
    name: iOS Release → TestFlight
    max_build_duration: 90
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: 3.38.1  # Последняя стабильная версия с полной поддержкой iOS 18
      xcode: 16.2      # Стабильный Xcode для iOS 18 (не beta!)
      cocoapods: default
      ios_signing:
        distribution_type: app_store

    scripts:
      - name: Очистка проекта
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Получение зависимостей
        script: flutter pub get

      - name: Установка CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --repo-update

      - name: Настройка подписи Xcode
        script: xcode-project use-profiles

      - name: Увеличение номера сборки
        script: |
          cd ios
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$APP_ID" 2>/dev/null || echo "0")
          agvtool new-version -all $((LATEST_BUILD + 1))

      - name: Сборка iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers
